"""
Build search-index.js from source/spell.json for full-text spell search.

Uses the same filter pipeline as build-spell-data.py (via spell_filter.py)
to ensure the spell set matches exactly.

Output: data/search-index.js containing window.SPELL_SEARCH_INDEX = [...]
Each entry: { aonId, name, text, traits, tradition, native_rank }
"""

import json
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)

sys.path.insert(0, SCRIPT_DIR)
from spell_filter import load_and_filter_spells, era

SPELL_JSON = os.path.join(PROJECT_ROOT, "source", "spell.json")
LEGACY_RENAMES_JSON = os.path.join(PROJECT_ROOT, "data", "legacy-renames.json")
OUTPUT_JS = os.path.join(PROJECT_ROOT, "data", "search-index.js")


def extract_aon_id(spell):
    sid = spell.get("id", "")
    if sid.startswith("spell-"):
        try:
            return int(sid[6:])
        except ValueError:
            pass
    return None


def clean_text(raw):
    if not raw:
        return ""
    text = re.sub(r'<[^>]+>', ' ', str(raw))
    text = re.sub(r'\*+', ' ', text)
    text = re.sub(r'\[([^\]]*)\]\([^)]*\)', r'\1', text)
    text = re.sub(r'[#>\-|`]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text.lower()


def build_search_entry(spell):
    aon_id = extract_aon_id(spell)
    if aon_id is None:
        return None

    name = spell.get("name", "")
    traits = [t.lower() for t in (spell.get("trait_raw") or [])]
    tradition = spell.get("tradition") or []
    native_rank = spell.get("level", 0)

    raw_text = spell.get("text", "") or ""
    text = clean_text(raw_text)

    if not text:
        text = name.lower() + " " + " ".join(traits)
        print("  Warning: spell %s (aonId %d) has no text field — using name+traits only." % (name, aon_id))

    return {
        "aonId": aon_id,
        "name": name,
        "text": text,
        "traits": traits,
        "tradition": tradition,
        "native_rank": native_rank,
    }


def main():
    print("Building search index...")
    print("Loading and filtering spells...")

    rank_spells = load_and_filter_spells(SPELL_JSON, LEGACY_RENAMES_JSON, verbose=True)

    entries = []
    skipped = 0
    no_text = 0

    for spell in rank_spells:
        entry = build_search_entry(spell)
        if entry is None:
            skipped += 1
            continue
        if not (spell.get("text") or ""):
            no_text += 1
        entries.append(entry)

    entries.sort(key=lambda e: (e["native_rank"], e["name"].lower()))

    print("\n%d search index entries built" % len(entries))
    if skipped:
        print("  WARNING: skipped %d spells with no parseable aonId" % skipped)
    if no_text:
        print("  %d spells had no text field (using name+traits fallback)" % no_text)

    print("Writing %s..." % OUTPUT_JS)
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by tools/build-search-index.py — do not edit manually\n")
        f.write("window.SPELL_SEARCH_INDEX = ")
        json.dump(entries, f, ensure_ascii=False, indent=None)
        f.write(";\n")

    file_size = os.path.getsize(OUTPUT_JS) / 1024 / 1024
    print("  %d entries written" % len(entries))
    print("  File size: %.1f MB" % file_size)
    print("Done.")


if __name__ == "__main__":
    main()
