"""
Merge Observations: reads consolidated.json and chain_registry.json,
writes mathfinder_summary, mathfinder_observations, mathfinder_reviewed,
replaced_by, and replaces fields onto matching spells in spell-data.js.

Cycle 20 — Part D of the Decision 013/015 pipeline.

Usage:
    py tools/merge-observations.py [--consolidated data/observations/consolidated.json] [--chains data/observations/chain_registry.json] [--spell-data data/spell-data.js]

Pipeline order: build-spell-data.py -> populate-spell-data.py --merge -> merge-observations.py
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone


def parse_args():
    parser = argparse.ArgumentParser(description="Merge observation data into spell-data.js")
    parser.add_argument("--consolidated", default="data/observations/consolidated.json",
                        help="Path to consolidated.json")
    parser.add_argument("--chains", default="data/observations/chain_registry.json",
                        help="Path to chain_registry.json")
    parser.add_argument("--spell-data", default="data/spell-data.js",
                        help="Path to spell-data.js (read + write)")
    return parser.parse_args()


def load_spell_data(path):
    with open(path, encoding="utf-8") as f:
        raw = f.read()
    lines = raw.split("\n", 1)
    rest = lines[1] if lines[0].startswith("//") else raw
    prefix = "window.SPELL_SCHEMA = "
    idx = rest.index(prefix)
    json_str = rest[idx + len(prefix):].rstrip().rstrip(";")
    schema = json.loads(json_str)
    return schema


def write_spell_data(path, schema):
    header = "// Auto-generated by tools/build-spell-data.py — do not edit manually\n"
    json_str = json.dumps(schema, ensure_ascii=False, separators=(",", ": "))
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("window.SPELL_SCHEMA = ")
        f.write(json_str)
        f.write(";\n")


def build_chain_data(chain_registry):
    """Build replaced_by and replaces entries from chain registry.

    Returns: {aon_id_str: {"replaced_by": [...], "replaces": [...]}}
    """
    result = {}

    def ensure(aon_id):
        sid = str(aon_id)
        if sid not in result:
            result[sid] = {"replaced_by": [], "replaces": []}
        return sid

    # Named chains
    for chain_key, chain in chain_registry.get("chains", {}).items():
        progression = chain["progression"]
        source = chain.get("source", "")
        function_desc = chain.get("function", "")

        for i, step in enumerate(progression):
            sid = ensure(step["aon_id"])

            if i < len(progression) - 1:
                next_step = progression[i + 1]
                result[sid]["replaced_by"].append({
                    "spell": next_step["spell"],
                    "aon_id": next_step["aon_id"],
                    "at_rank": next_step["from_rank"],
                    "chain": chain_key,
                    "source": source,
                    "reason": function_desc,
                })

            if i > 0:
                prev_step = progression[i - 1]
                result[sid]["replaces"].append({
                    "spell": prev_step["spell"],
                    "aon_id": prev_step["aon_id"],
                    "at_rank": step["from_rank"],
                    "chain": chain_key,
                    "source": source,
                    "reason": function_desc,
                })

    # Standalone pairs
    for pair in chain_registry.get("standalone_pairs", []):
        rel = pair["relationship"]
        a_id = ensure(pair["spell_a_aon_id"])
        b_id = ensure(pair["spell_b_aon_id"])
        at_rank = pair.get("at_rank")
        source = pair.get("source", "")
        reason = pair.get("reason", "")

        if rel in ("replaces", "upgrades_to", "outclassed_by"):
            result[a_id]["replaced_by"].append({
                "spell": pair["spell_b"],
                "aon_id": pair["spell_b_aon_id"],
                "at_rank": at_rank,
                "chain": None,
                "source": source,
                "reason": reason,
            })
            result[b_id]["replaces"].append({
                "spell": pair["spell_a"],
                "aon_id": pair["spell_a_aon_id"],
                "at_rank": at_rank,
                "chain": None,
                "source": source,
                "reason": reason,
            })
        elif rel == "competes_with":
            result[a_id]["replaced_by"].append({
                "spell": pair["spell_b"],
                "aon_id": pair["spell_b_aon_id"],
                "at_rank": at_rank,
                "chain": None,
                "source": source,
                "reason": reason,
            })
            result[b_id]["replaced_by"].append({
                "spell": pair["spell_a"],
                "aon_id": pair["spell_a_aon_id"],
                "at_rank": at_rank,
                "chain": None,
                "source": source,
                "reason": reason,
            })
            result[a_id]["replaces"].append({
                "spell": pair["spell_b"],
                "aon_id": pair["spell_b_aon_id"],
                "at_rank": at_rank,
                "chain": None,
                "source": source,
                "reason": reason,
            })
            result[b_id]["replaces"].append({
                "spell": pair["spell_a"],
                "aon_id": pair["spell_a_aon_id"],
                "at_rank": at_rank,
                "chain": None,
                "source": source,
                "reason": reason,
            })

    return result


def main():
    args = parse_args()

    # Load inputs
    consolidated_exists = os.path.exists(args.consolidated)
    chains_exists = os.path.exists(args.chains)

    consolidated = None
    if consolidated_exists:
        with open(args.consolidated, encoding="utf-8") as f:
            consolidated = json.load(f)
        print(f"Loaded consolidated.json: {consolidated['summary_count']} summaries, "
              f"{consolidated['category_only_count']} category-only")
    else:
        print(f"WARNING: {args.consolidated} not found. Observation fields will be defaults.")

    chain_registry = None
    chain_data = {}
    if chains_exists:
        with open(args.chains, encoding="utf-8") as f:
            chain_registry = json.load(f)
        chain_data = build_chain_data(chain_registry)
        print(f"Loaded chain_registry.json: {chain_registry['chain_count']} chains, "
              f"{chain_registry['pair_count']} standalone pairs")
        print(f"Chain/pair data affects {len(chain_data)} spells")
    else:
        print(f"WARNING: {args.chains} not found. Chain fields will be defaults.")

    # Load spell-data.js
    schema = load_spell_data(args.spell_data)
    spells = schema["spells"]
    print(f"Loaded spell-data.js: {len(spells)} spells")

    # Merge
    obs_applied = 0
    chain_applied = 0
    summary_applied = 0

    for spell in spells:
        aon_id = str(spell["aonId"])

        # Observation fields
        if consolidated and aon_id in consolidated["spells"]:
            entry = consolidated["spells"][aon_id]
            spell["mathfinder_summary"] = entry["mathfinder_summary"]
            spell["mathfinder_reviewed"] = entry["mathfinder_reviewed"]
            # Strip source_type and applies_to from observations for export
            exported_obs = []
            for obs in entry.get("observations", []):
                exported_obs.append({
                    "source": obs["source"],
                    "observation": obs["observation"],
                })
            spell["mathfinder_observations"] = exported_obs
            obs_applied += 1
            if entry["mathfinder_summary"]:
                summary_applied += 1
        else:
            spell["mathfinder_summary"] = None
            spell["mathfinder_observations"] = []
            spell["mathfinder_reviewed"] = False

        # Chain fields
        if aon_id in chain_data:
            cd = chain_data[aon_id]
            spell["replaced_by"] = cd["replaced_by"] if cd["replaced_by"] else []
            spell["replaces"] = cd["replaces"] if cd["replaces"] else []
            chain_applied += 1
        else:
            spell["replaced_by"] = []
            spell["replaces"] = []

    # Write
    write_spell_data(args.spell_data, schema)

    print(f"\nMerge complete:")
    print(f"  Spells with observations: {obs_applied}")
    print(f"  Spells with summaries: {summary_applied}")
    print(f"  Spells with chain data: {chain_applied}")
    print(f"  All {len(spells)} spells touched (defaults applied to non-observation spells)")
    print(f"\nWrote {args.spell_data}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
