"""
Merge spell.json (full catalog) + curated.json (Mathfinder ratings) → data/spells.js
Outputs a browser-loadable JS file assigning window.SPELL_DATA.
"""

import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)

SPELL_JSON = os.path.join(PROJECT_ROOT, "source", "spell.json")
CURATED_JSON = os.path.join(PROJECT_ROOT, "data", "curated.json")
OUTPUT_JS = os.path.join(PROJECT_ROOT, "data", "spells.js")


def extract_aon_id(spell):
    """Extract numeric AoN ID from spell's id field (e.g., 'spell-1536' → 1536)."""
    sid = spell.get("id", "")
    if sid.startswith("spell-"):
        try:
            return int(sid[6:])
        except ValueError:
            pass
    return None


def slim_spell(spell):
    """Extract only the fields the app needs from a full spell.json entry."""
    return {
        "name": spell.get("name", ""),
        "aonId": extract_aon_id(spell),
        "rank": spell.get("level", 0),
        "traditions": [t.lower() for t in spell.get("tradition", [])],
        "traits": spell.get("trait_raw", []),
        "save": spell.get("saving_throw", ""),
        "actions": spell.get("actions", ""),
        "summary": spell.get("summary", ""),
        "rarity": spell.get("rarity", "common"),
        "target": spell.get("target", ""),
        "range": spell.get("range_raw", ""),
        "url": spell.get("url", ""),
    }


def build_curated_index(curated_data):
    """Build a lookup: (aonId, tradition, rank, role) → curated entry."""
    index_by_aon = {}
    index_by_name = {}

    for tradition, entries in curated_data.get("traditions", {}).items():
        for entry in entries:
            aon_id = entry.get("aonId")
            if aon_id:
                key = (aon_id, tradition)
                if key not in index_by_aon:
                    index_by_aon[key] = []
                index_by_aon[key].append(entry)

            name_key = (entry["name"].lower(), tradition)
            if name_key not in index_by_name:
                index_by_name[name_key] = []
            index_by_name[name_key].append(entry)

    return index_by_aon, index_by_name


def main():
    print("Loading spell.json...")
    with open(SPELL_JSON, 'r', encoding='utf-8') as f:
        all_spells = json.load(f)
    print(f"  {len(all_spells)} spells loaded")

    print("Loading curated.json...")
    with open(CURATED_JSON, 'r', encoding='utf-8') as f:
        curated_data = json.load(f)

    curated_by_aon, curated_by_name = build_curated_index(curated_data)
    tag_defs = curated_data.get("tagDefs", {})

    total_curated_matches = 0
    merged = []

    for spell in all_spells:
        slim = slim_spell(spell)
        if slim["aonId"] is None:
            continue

        # Check if this spell has curated entries for any tradition
        curated_entries = []
        for tradition in slim["traditions"]:
            key = (slim["aonId"], tradition)
            if key in curated_by_aon:
                curated_entries.extend(curated_by_aon[key])

        if curated_entries:
            slim["curated"] = True
            slim["curatedEntries"] = curated_entries
            total_curated_matches += 1
        else:
            slim["curated"] = False

        merged.append(slim)

    # Sort: curated first, then alphabetical
    merged.sort(key=lambda s: (0 if s["curated"] else 1, s["name"].lower()))

    output = {
        "spells": merged,
        "tagDefs": tag_defs,
        "curatedByTradition": curated_data.get("traditions", {}),
    }

    print(f"\nWriting {OUTPUT_JS}...")
    with open(OUTPUT_JS, 'w', encoding='utf-8') as f:
        f.write("// Auto-generated by tools/merge-spells.py — do not edit manually\n")
        f.write("window.SPELL_DATA = ")
        json.dump(output, f, ensure_ascii=False)
        f.write(";\n")

    file_size = os.path.getsize(OUTPUT_JS) / 1024 / 1024
    print(f"  {len(merged)} spells merged ({total_curated_matches} with curated data)")
    print(f"  File size: {file_size:.1f} MB")
    print("Done.")


if __name__ == "__main__":
    main()
